# Generated by Django 3.1.2 on 2020-12-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onelesson',
            name='comment_teacher',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
